services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\EventBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaEventBundle.php'
